Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,11 +23,19 @@ export_env_dir() {
   fi
 }
 
+echo "-----> Listing HEROKU_ environment variables"
+echo "HEROKU_APP_ID:           $HEROKU_APP_ID"
+echo "HEROKU_APP_NAME:         $HEROKU_APP_NAME"
+echo "HEROKU_DYNO_ID:          $HEROKU_DYNO_ID"
+echo "HEROKU_RELEASE_VERSION:  $HEROKU_RELEASE_VERSION"
+echo "HEROKU_SLUG_COMMIT:      $HEROKU_SLUG_COMMIT"
+echo "HEROKU_SLUG_DESCRIPTION: $HEROKU_SLUG_DESCRIPTION"
+
 export_env_dir $3
 
 # Enable verbose debugging if configured to -- though this has to come after
 # we've loaded environment configs.
-if [ -n "$BUILDPACK_VERBOSE" ]; then
+if [ -n "${BUILDPACK_VERBOSE+1}" ]; then
   set -x
 fi
 
@@ -37,7 +45,7 @@ BUILDPACK_DIR=$(cd -P -- "$(dirname -- "$0")" && cd .. && pwd -P)
 # Get the directory our app is checked out in (the "BUILD_DIR"), passed by Heroku
 APP_CHECKOUT_DIR=$1
 CACHE_DIR=$2
-if [ -n "$BUILDPACK_CLEAR_CACHE" ]; then
+if [ -n "${BUILDPACK_CLEAR_CACHE+1}" ]; then
   echo "-----> Clearing cache dir."
   rm -rf "$CACHE_DIR/*"
 fi
@@ -168,23 +176,41 @@ PATH="$METEOR_DIR/.meteor:`dirname $METEOR_NPM`:$COMPILE_DIR/bin:$PATH"
 echo "-----> Using node: `$NODE --version`"
 echo "----->    and npm: `$METEOR_NPM --version`"
 
-# If we use npm on root, run npm install.  Don't use `--production` here, as we
-# may need devDependencies (e.g. webpack) in order to build the meteor app.
+# If we use npm on root, run npm install.  Don't use `--production` here, if we
+# need devDependencies (e.g. webpack) in order to build the meteor app.
 if [ -e "$APP_SOURCE_DIR"/package.json ]; then
   $METEOR_NPM install
 fi
+
+# Temporary fix for https://github.com/RocketChat/Rocket.Chat/issues/6444
+# Try to add an existing package and let it fail, but the build command will work ¯\_(ツ)_/¯
+# Allow non-zero return since we know it will fail
+set +e
+METEOR add rocketchat:lib
+set -e
 
 # Related to https://github.com/meteor/meteor/issues/2796 and
 # https://github.com/meteor/meteor/issues/2606.  Some packages only build their
 # assets at runtime, and thus they are not available for bundling unless meteor
 # has been launched.  To opt-in to this, set BUILDPACK_PRELAUNCH_METEOR=1.
-if [ -n "$BUILDPACK_PRELAUNCH_METEOR" ]; then
+if [ -n "${BUILDPACK_PRELAUNCH_METEOR+1}" ]; then
   echo "-----> BUILDPACK_PRELAUNCH_METEOR: Pre-launching meteor to build packages assets"
   # Remove the Android platform because it fails due to the Android tools not
   # being installed, but leave the iOS platform because it's ignored.
   METEOR remove-platform android || true
   HOME=$METEOR_DIR timeout -s9 60 $METEOR_DIR/.meteor/meteor --settings settings.json || true
 fi
+
+#
+# Before Bundling
+#
+
+# source scripts in 'before' dir, if any.  Create them for custom stuff like
+# binary dependencies, additional environment settings, etc.
+echo "-----> Running before bundling"
+for file in `ls "$BUILDPACK_DIR"/before | sort`; do
+  . "$BUILDPACK_DIR"/before/$file
+done
 
 # Now on to bundling. Don't put the bundle in $APP_CHECKOUT_DIR during
 # bundling, or it will recurse, trying to bundle up its own bundling.
@@ -233,7 +259,7 @@ done
 #
 # Clear cache after build is done
 #
-if [ -n "$BUILDPACK_CLEAR_CACHE" ]; then
+if [ -n "${BUILDPACK_CLEAR_CACHE+1}" ]; then
   echo "-----> Clearing cache dir."
   rm -rf $METEOR_DIR
 fi
